# Generated by Django 3.2.22 on 2023-10-23 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fp_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
