# Generated by Django 3.2.22 on 2023-10-26 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fp_blog', '0002_action_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article_actions', to='auth.user'),
            preserve_default=False,
        ),
    ]
