# Generated by Django 3.2.22 on 2023-10-30 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fp_blog', '0003_action_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['article', 'action_seq']},
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='admin', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
