# Generated by Django 3.2.22 on 2023-11-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fp_blog', '0006_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
