# Generated by Django 3.2.22 on 2023-11-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_blog', '0007_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_url',
            field=models.URLField(blank=True),
        ),
    ]
