# Generated by Django 3.2.22 on 2023-11-15 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_blog', '0008_action_action_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
