# Generated by Django 3.2.22 on 2023-11-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_blog', '0009_alter_article_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
