# Generated by Django 4.2.7 on 2024-11-09 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_blog', '0013_alter_action_article_alter_action_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('O', 'Other'), ('U', 'Unanswered')], max_length=1)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(120)])),
                ('income', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('number_children', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('income_type', models.CharField(max_length=100)),
                ('main_income_source', models.CharField(max_length=100)),
                ('other_income_sources', models.TextField(blank=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=50)),
                ('accommodation_status', models.CharField(choices=[('homeless', 'Homeless'), ('renting', 'Renting'), ('living_with_family', 'Living with Family'), ('own_home_mortgage', 'Own my own home but paying mortgage'), ('own_home_no_mortgage', 'Own my own home and not paying mortgage')], default='available', max_length=50)),
                ('accommodation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_adults_living_with', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(45)])),
                ('financial_admin_for', models.CharField(max_length=100)),
                ('life_stage', models.CharField(max_length=100)),
                ('life_events', models.TextField(blank=True)),
                ('welfare_schemes', models.CharField(max_length=100)),
            ],
        ),
    ]
