# Generated by Django 3.2.22 on 2023-11-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_personal', '0002_auto_20231105_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='completed_on',
            field=models.DateTimeField(),
        ),
    ]
