# Generated by Django 3.2.22 on 2023-11-05 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fp_blog', '0005_alter_article_likes'),
        ('fp_personal', '0005_alter_useraction_completed_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('favourite_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_favourite', to='fp_blog.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'created_on'],
            },
        ),
    ]
