# Generated by Django 3.2.22 on 2023-11-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fp_personal', '0007_alter_userfavourite_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_on']},
        ),
    ]
