# Generated by Django 3.2.22 on 2023-11-11 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fp_blog', '0006_comment_user'),
        ('fp_personal', '0008_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraction',
            options={'ordering': ['user', 'user_action_seq', 'created_on']},
        ),
        migrations.AlterField(
            model_name='useraction',
            name='observation',
            field=models.CharField(default='Results:  ', max_length=200),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='parent_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='fp_blog.article'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='fp_personal.userprofile'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='user_action_desc',
            field=models.CharField(default='Action descripton:  ', max_length=200),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='user_action_taken',
            field=models.CharField(default='Done so far:  ', max_length=200),
        ),
    ]
