# Generated by Django 3.2.22 on 2023-11-11 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fp_blog', '0006_comment_user'),
        ('fp_personal', '0011_alter_useraction_user_action_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='parent_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_artice', to='fp_blog.article'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='user_action_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_action', to='fp_blog.action'),
        ),
    ]
