# Generated by Django 3.2.22 on 2023-11-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fp_blog', '0006_comment_user'),
        ('fp_personal', '0012_auto_20231111_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='parent_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_article', to='fp_blog.article'),
        ),
    ]
