# Generated by Django 3.2.22 on 2023-11-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_personal', '0015_useraction_user_action_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(default='Console', max_length=30)),
                ('email', models.EmailField(default='your_email@gmail.com', max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, max_length=500)),
                ('followup', models.TextField(blank=True, max_length=500)),
                ('completed', models.BooleanField()),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['person', '-created_on'],
            },
        ),
    ]
