# Generated by Django 3.2.22 on 2023-11-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_personal', '0016_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='type',
            field=models.TextField(default='F', max_length=1),
        ),
    ]
