# Generated by Django 4.2.7 on 2024-08-19 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fp_blog', '0013_alter_action_article_alter_action_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fp_personal', '0017_auto_20231119_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='parent_article',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='parent_article', to='fp_blog.article'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='user_action_desc',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='parent_action', to='fp_blog.action'),
        ),
    ]
