# Generated by Django 4.2.7 on 2024-11-25 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='effective_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 22, 37, 49, 564149)),
        ),
        migrations.AlterField(
            model_name='course',
            name='effective_to',
            field=models.DateTimeField(default=datetime.datetime(2034, 11, 25, 22, 37, 49, 563178)),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='version',
            field=models.CharField(max_length=3),
        ),
    ]
