# Generated by Django 4.2.7 on 2024-11-25 22:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fp_courses', '0002_alter_cohort_effective_to_alter_course_effective_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='effective_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 22, 43, 55, 113069)),
        ),
        migrations.AlterField(
            model_name='course',
            name='effective_to',
            field=models.DateTimeField(default=datetime.datetime(2034, 11, 25, 22, 43, 55, 112046)),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='course_code',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='course_contents', to='fp_courses.course'),
        ),
    ]
