# Generated by Django 4.2.7 on 2024-12-20 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fp_courses', '0002_alter_quiz_quiz_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='author',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='cohort',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='cohort_course', to='fp_courses.course'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='quiz',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_quiz', to='fp_courses.quiz'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='effective_from',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_code',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('sequence_number', models.IntegerField()),
                ('score', models.FloatField()),
                ('completed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fp_courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
