# Generated by Django 4.2.7 on 2024-11-25 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_courses', '0003_alter_cohort_effective_to_alter_course_effective_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='effective_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 22, 43, 58, 839991)),
        ),
        migrations.AlterField(
            model_name='course',
            name='effective_to',
            field=models.DateTimeField(default=datetime.datetime(2034, 11, 25, 22, 43, 58, 839026)),
        ),
    ]
