# Generated by Django 4.2.7 on 2024-11-26 00:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fp_courses', '0005_alter_cohort_effective_to_alter_course_effective_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='effective_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 0, 44, 20, 106548)),
        ),
        migrations.AlterField(
            model_name='course',
            name='effective_to',
            field=models.DateTimeField(default=datetime.datetime(2034, 11, 26, 0, 44, 20, 105448)),
        ),
        migrations.CreateModel(
            name='CohortUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_users', to='fp_courses.cohort')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='learner_cohorts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cohort_code', 'user'],
                'unique_together': {('cohort_code', 'user')},
            },
        ),
    ]
