# Generated by Django 4.2.7 on 2024-11-26 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_courses', '0006_alter_cohort_effective_to_alter_course_effective_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_seq',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='effective_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 26, 1, 0, 7, 275128)),
        ),
        migrations.AlterField(
            model_name='course',
            name='effective_to',
            field=models.DateTimeField(default=datetime.datetime(2034, 11, 26, 1, 0, 7, 274040)),
        ),
    ]
