# Generated by Django 4.2.7 on 2024-11-26 08:32

from django.conf import settings
from django.db import migrations, models
import fp_courses.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fp_courses', '0008_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='cohort_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='effective_from',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='effective_to',
            field=models.DateField(default=fp_courses.models.today_plus_one_year),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='updated_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='effective_from',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='effective_to',
            field=models.DateField(default=fp_courses.models.today_plus_10_years),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
