# Generated by Django 4.2.7 on 2024-11-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_courses', '0010_delete_cohortuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('question_text', models.CharField(default='Question text goes here?', max_length=200)),
                ('ans1_text', models.CharField(default='Answer1 goes here', max_length=200)),
                ('ans2_text', models.CharField(default='Answer2 goes here', max_length=200)),
                ('ans3_text', models.CharField(default='Answer3 goes here', max_length=200)),
                ('ans4_text', models.CharField(default='Answer4 goes here', max_length=200)),
                ('correct_ans', models.IntegerField()),
                ('explanation', models.CharField(default='Correct answer is X:  This is because ......', max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
            ],
            options={
                'ordering': ['quiz_code'],
            },
        ),
    ]
