# Generated by Django 4.2.7 on 2024-12-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_courses', '0014_quiz_author_quiz_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_code',
            field=models.CharField(unique=True),
        ),
    ]
