# Generated by Django 4.2.7 on 2024-12-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fp_courses', '0015_course_id_quiz_id_alter_course_course_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_code',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
